### PR TITLE
Update NFT-RFC-002-use-cases.md

### PR DESCRIPTION
**Pull request by dayakarreddyn**
Added 4.7 Media IP & Distribution Use-case.

### CODE REVIEW

**Comment by jandrieu** [comment]
Look like there is a conflict that needs to be resolved but this should be ready to merge once those conflicts are fixed.

**Review by ig-shaun — APPROVED** [review]
User story section added - to be populated

**Comment by lawyerphil** [comment]
Disclaimer: This comment was prepared for general information purposes only. The information presented is not legal advice, is not to be acted on as such, may not be current and is subject to change without notice.

Just an FYI for the theater ticket use case story. The ticket itself is a revocable license given by the theater to the ticket holder. The theater thus needs to retain the ability to revoke the license from the ticket holder regardless of a breach of contract or not since it is revocable. This is how almost all tickets work in the US. 

For example: if Vicky and Stephen go to the theater the night of the event and a famous celebrity needs tickets, the theater company may legally revoke the tickets (revoking the licenses) from Vicky and Stephen and provide the tickets to the celebrity to see the play. Vicky and Stephen would be legally entitled to compensation, but they have no legal right to the seats the night of the show, the ticket is only a revocable license.

**Comment by ig-shaun** [comment]
Moved to PR 10

**Pull request closed without merging**
